# -*- coding: utf-8 -*-
"""Sesli dialoqlar - anlasilan giris (comprehensible input) ucun.
Her sətir: (danisan A/B, ingiliscə, azərbaycanca)
"""

DIALOGS = [
{"t":"Səhər salamlaşma","lv":"A1","d":"Ofisdə həmkarla qısa söhbət","l":[
 ("A","Good morning, Samir.","Sabahın xeyir, Samir."),
 ("B","Morning, Leyla. How are you?","Sabahın xeyir, Leyla. Necəsən?"),
 ("A","Not bad, thanks. A bit tired.","Pis deyil, sağ ol. Bir az yorğunam."),
 ("B","Long night?","Gecə uzun oldu?"),
 ("A","Yes, I was fixing the printer until ten.","Bəli, saat ona qədər printeri düzəldirdim."),
 ("B","Did you manage to fix it?","Düzəltməyi bacardın?"),
 ("A","In the end, yes.","Sonda, bəli."),
 ("B","Well done. Coffee?","Afərin. Qəhvə?"),
 ("A","That would be great, thanks.","Əla olardı, sağ ol.")]},

{"t":"Kafedə sifariş","lv":"A1","d":"Sadə sifariş vermək","l":[
 ("A","Hello, what can I get you?","Salam, nə istəyirsiniz?"),
 ("B","Hi. Could I have a black coffee, please?","Salam. Bir qara qəhvə ola bilər?"),
 ("A","Small or large?","Kiçik yoxsa böyük?"),
 ("B","Large, please. And do you have any sandwiches?","Böyük, zəhmət olmasa. Sendviçiniz var?"),
 ("A","We have chicken and cheese.","Toyuqlu və pendirli var."),
 ("B","I will take the chicken one.","Toyuqlusunu götürərəm."),
 ("A","To eat in or take away?","Burada yeyəcəksiniz, yoxsa özünüzlə?"),
 ("B","Take away, please. How much is it?","Özümlə, zəhmət olmasa. Neçəyədir?"),
 ("A","That is eight manats fifty.","Səkkiz manat əlli qəpik."),
 ("B","Here you are. Thank you.","Buyurun. Təşəkkür edirəm.")]},

{"t":"Yol soruşmaq","lv":"A1","d":"Küçədə istiqamət soruşmaq","l":[
 ("A","Excuse me, do you speak English?","Bağışlayın, ingiliscə danışırsınız?"),
 ("B","A little, yes.","Bir az, bəli."),
 ("A","I am looking for the metro station.","Metro stansiyasını axtarıram."),
 ("B","Go straight ahead and turn left at the traffic light.","Düz gedin və svetoforda sola dönün."),
 ("A","Is it far?","Uzaqdır?"),
 ("B","No, about five minutes on foot.","Xeyr, piyada təxminən beş dəqiqə."),
 ("A","And which line goes to the airport?","Hansı xətt hava limanına gedir?"),
 ("B","You need to change at the central station.","Mərkəzi stansiyada dəyişməlisiniz."),
 ("A","Thank you very much.","Çox sağ olun."),
 ("B","You are welcome. Have a good day.","Dəyməz. Gününüz xeyir.")]},

{"t":"Mağazada alış-veriş","lv":"A1","d":"Ölçü və qiymət soruşmaq","l":[
 ("A","Can I help you?","Kömək edə bilərəm?"),
 ("B","Yes, I am looking for a white shirt.","Bəli, ağ köynək axtarıram."),
 ("A","What size do you need?","Hansı ölçü lazımdır?"),
 ("B","Medium, I think. Can I try it on?","Orta, deyəsən. Geyib baxa bilərəm?"),
 ("A","Of course. The fitting room is over there.","Əlbəttə. Geyinmə otağı oradadır."),
 ("B","It is a bit tight. Do you have a larger one?","Bir az dardır. Daha böyüyü var?"),
 ("A","Let me check. Yes, here you are.","Yoxlayım. Bəli, buyurun."),
 ("B","This one fits. How much is it?","Bu yaxşı oturur. Neçəyədir?"),
 ("A","Forty-five manats. Cash or card?","Qırx beş manat. Nağd, yoxsa kart?"),
 ("B","Card, please.","Kart, zəhmət olmasa.")]},

{"t":"Telefon zəngi","lv":"A2","d":"İş zəngini qəbul etmək","l":[
 ("A","Good afternoon, IT department, Samir speaking.","Günortanız xeyir, İT şöbəsi, Samir danışır."),
 ("B","Hi Samir, this is Nigar from accounting.","Salam Samir, mühasibatlıqdan Nigardır."),
 ("A","Hi Nigar, how can I help?","Salam Nigar, necə kömək edə bilərəm?"),
 ("B","I cannot log into the system this morning.","Bu səhər sistemə girə bilmirəm."),
 ("A","What error message do you get?","Hansı xəta mesajı çıxır?"),
 ("B","It says the account is locked.","Hesabın kilidləndiyini yazır."),
 ("A","I see. Let me unlock it for you.","Anladım. İcazə verin kilidini açım."),
 ("B","How long will it take?","Nə qədər çəkəcək?"),
 ("A","Just a moment. Try again now.","Bir dəqiqə. İndi bir də cəhd edin."),
 ("B","It works. Thank you so much.","İşləyir. Çox sağ olun."),
 ("A","No problem. Let me know if it happens again.","Problem yoxdur. Təkrarlansa, mənə deyin.")]},

{"t":"Hava limanında qeydiyyat","lv":"A2","d":"Uçuşa qeydiyyat və baqaj","l":[
 ("A","Good evening. Your passport, please.","Axşamınız xeyir. Pasportunuz, zəhmət olmasa."),
 ("B","Here it is.","Buyurun."),
 ("A","Are you checking in any luggage?","Baqaj təhvil verirsiniz?"),
 ("B","Just one suitcase.","Yalnız bir çamadan."),
 ("A","Please put it on the belt. It is twenty-three kilos.","Xahiş edirəm lentə qoyun. İyirmi üç kiloqramdır."),
 ("B","Is that within the limit?","Bu limitə uyğundur?"),
 ("A","Yes, the limit is twenty-five.","Bəli, limit iyirmi beşdir."),
 ("B","Which gate is it?","Hansı qapıdır?"),
 ("A","Gate twelve. Boarding starts at nine forty.","On ikinci qapı. Miniş doqquz qırxda başlayır."),
 ("B","And is the flight on time?","Uçuş vaxtındadır?"),
 ("A","So far, yes. Have a pleasant flight.","Hələlik bəli. Xoş uçuşlar.")]},

{"t":"Otelə yerləşmə","lv":"A2","d":"Rezervasiya və otaq məsələləri","l":[
 ("A","Good evening. Do you have a reservation?","Axşamınız xeyir. Rezervasiyanız var?"),
 ("B","Yes, under the name Aliyev.","Bəli, Əliyev adına."),
 ("A","Let me check. A single room for three nights?","Yoxlayım. Üç gecəyə tək otaq?"),
 ("B","That is right.","Düzdür."),
 ("A","Could I have your passport, please?","Pasportunuzu ala bilərəm?"),
 ("B","Here you are. Is breakfast included?","Buyurun. Səhər yeməyi daxildir?"),
 ("A","Yes, from seven to ten in the restaurant.","Bəli, restoranda yeddidən ona qədər."),
 ("B","What is the wifi password?","Wifi şifrəsi nədir?"),
 ("A","It is written on your key card.","Otaq kartınızın üstündə yazılıb."),
 ("B","Great. What time is check out?","Əla. Çıxış saatı neçədir?"),
 ("A","Eleven o'clock. Enjoy your stay.","Saat on birdə. Xoş qalın.")]},

{"t":"Yeni həmkarla tanışlıq","lv":"A2","d":"Özünü təqdim etmək","l":[
 ("A","Hi, you must be the new engineer.","Salam, siz yəqin yeni mühəndissiniz."),
 ("B","Yes, I am Rashad. Nice to meet you.","Bəli, mən Rəşadam. Tanış olmağıma şadam."),
 ("A","Nice to meet you too. I am Samir, head of IT.","Mən də şadam. Mən Samir, İT rəhbəri."),
 ("B","Great to meet you. I started on Monday.","Çox şadam. Bazar ertəsi başlamışam."),
 ("A","How are you settling in?","Uyğunlaşırsınız?"),
 ("B","Well, thanks. Everyone has been very helpful.","Yaxşı, sağ olun. Hamı çox kömək edir."),
 ("A","What did you do before this?","Bundan əvvəl nə işlə məşğul idiniz?"),
 ("B","I worked at a telecom company for four years.","Dörd il telekom şirkətində işləmişəm."),
 ("A","That experience will be useful here.","O təcrübə burada faydalı olacaq."),
 ("B","I hope so. Who should I talk to about access rights?","Ümid edirəm. Giriş hüquqları barədə kimlə danışım?"),
 ("A","Talk to me. I will set it up today.","Mənimlə. Bu gün quraram.")]},

{"t":"Həkimə müraciət","lv":"A2","d":"Şikayəti izah etmək","l":[
 ("A","Good morning. What seems to be the problem?","Sabahınız xeyir. Nə problem var?"),
 ("B","I have had a headache for three days.","Üç gündür başım ağrıyır."),
 ("A","Is it constant or does it come and go?","Daimidir, yoxsa gəlib-gedir?"),
 ("B","It comes and goes, mostly in the evening.","Gəlib-gedir, əsasən axşamlar."),
 ("A","Are you sleeping well?","Yaxşı yatırsınız?"),
 ("B","Not really. About five hours a night.","Elə də yox. Gecədə təxminən beş saat."),
 ("A","Do you spend a lot of time at a screen?","Ekran qarşısında çox vaxt keçirirsiniz?"),
 ("B","Yes, around ten hours a day.","Bəli, gündə təxminən on saat."),
 ("A","That is likely the cause. Take regular breaks.","Yəqin səbəb budur. Müntəzəm fasilə verin."),
 ("B","Should I take anything for the pain?","Ağrı üçün nəsə qəbul edim?"),
 ("A","Only if it is severe. Come back in a week.","Yalnız şiddətli olsa. Bir həftədən sonra gəlin.")]},

{"t":"İclası planlaşdırmaq","lv":"B1","d":"Vaxt razılaşdırmaq","l":[
 ("A","Are you free sometime this week?","Bu həftə vaxtınız olacaq?"),
 ("B","Let me check my calendar. What is it about?","Təqvimimə baxım. Nə barədədir?"),
 ("A","I would like to go through the migration plan.","Miqrasiya planını nəzərdən keçirmək istərdim."),
 ("B","How long do you need?","Nə qədər vaxt lazımdır?"),
 ("A","About forty minutes should be enough.","Təxminən qırx dəqiqə kifayət edər."),
 ("B","Tuesday at eleven works for me.","Çərşənbə axşamı saat on bir mənə uyğundur."),
 ("A","Perfect. Shall I send an invite?","Əla. Dəvət göndərim?"),
 ("B","Yes, please. And could you share the plan beforehand?","Bəli, zəhmət olmasa. Planı əvvəlcədən göndərə bilərsiniz?"),
 ("A","Of course. I will send it today.","Əlbəttə. Bu gün göndərəcəyəm."),
 ("B","Great. Should we invite the vendor as well?","Əla. Təchizatçını da dəvət edək?"),
 ("A","Good point. I will loop them in.","Yaxşı fikir. Onları da əlavə edərəm.")]},

{"t":"Texniki dəstək zəngi","lv":"B1","d":"Problemi izah və həll etmək","l":[
 ("A","Support desk, how can I help?","Dəstək xidməti, necə kömək edə bilərəm?"),
 ("B","Our internet banking site is returning an error.","İnternet bankçılıq saytımız xəta qaytarır."),
 ("A","Could you tell me the exact error code?","Dəqiq xəta kodunu deyə bilərsiniz?"),
 ("B","It shows five twenty-five.","Beş yüz iyirmi beş göstərir."),
 ("A","That usually points to a certificate issue.","Bu adətən sertifikat problemini göstərir."),
 ("B","We renewed the certificate last month.","Sertifikatı keçən ay yeniləmişik."),
 ("A","Was it installed on the load balancer as well?","Yük balanslaşdırıcıda da quraşdırıldı?"),
 ("B","I am not sure. Let me check.","Əmin deyiləm. Yoxlayım."),
 ("A","Take your time.","Tələsməyin."),
 ("B","You were right. The old one is still there.","Haqlı idiniz. Köhnəsi hələ də oradadır."),
 ("A","Replace it and restart the service.","Onu dəyişin və xidməti yenidən başladın."),
 ("B","It is working now. Thanks for your help.","İndi işləyir. Kömək üçün təşəkkür.")]},

{"t":"Layihə statusu görüşü","lv":"B1","d":"İrəliləyiş hesabatı vermək","l":[
 ("A","Let us start with the status update.","Status yeniləməsi ilə başlayaq."),
 ("B","Sure. We completed the first two modules.","Əlbəttə. İlk iki modulu tamamladıq."),
 ("A","Are we still on schedule?","Cədvələ uyğun gedirik?"),
 ("B","More or less. We are two days behind.","Az-çox. İki gün geridəyik."),
 ("A","What caused the delay?","Gecikməyə nə səbəb oldu?"),
 ("B","We ran into an issue with the API integration.","API inteqrasiyası ilə problem yaşadıq."),
 ("A","Has it been resolved?","Həll olundu?"),
 ("B","Yes, it turned out to be a header name.","Bəli, məlum oldu ki, başlıq adı imiş."),
 ("A","Good. Can we make up the two days?","Yaxşı. İki günü bərpa edə bilərik?"),
 ("B","I believe so, if nothing else comes up.","Düşünürəm ki, bəli, başqa problem çıxmasa."),
 ("A","Keep me posted. Anything you need from me?","Xəbərdar edin. Məndən nəsə lazımdır?"),
 ("B","Just approval for the extra test environment.","Yalnız əlavə test mühiti üçün təsdiq.")]},

{"t":"Şikayəti həll etmək","lv":"B1","d":"Narazı müştəri ilə danışmaq","l":[
 ("A","I have been waiting three days for a reply.","Üç gündür cavab gözləyirəm."),
 ("B","I am very sorry about that. Let me look into it.","Buna görə çox üzr istəyirəm. Araşdırım."),
 ("A","This is the second time this month.","Bu ay ikinci dəfədir."),
 ("B","I understand your frustration.","Narazılığınızı başa düşürəm."),
 ("A","I just want to know when it will be fixed.","Sadəcə nə vaxt düzələcəyini bilmək istəyirəm."),
 ("B","I can see your ticket here. It was not escalated.","Müraciətinizi görürəm. Yuxarı qaldırılmayıb."),
 ("A","So it was sitting there for three days?","Yəni üç gün orada qalıb?"),
 ("B","Unfortunately, yes. That should not have happened.","Təəssüf ki, bəli. Bu baş verməməli idi."),
 ("A","What are you going to do about it?","Bu barədə nə edəcəksiniz?"),
 ("B","I am taking it personally and will call you by five.","Şəxsən öz üzərimə götürürəm və beşə qədər zəng edəcəyəm."),
 ("A","I appreciate that.","Bunu qiymətləndirirəm."),
 ("B","Again, I apologise for the delay.","Bir daha gecikməyə görə üzr istəyirəm.")]},

{"t":"Vendorla qiymət danışığı","lv":"B2","d":"Şərtləri müzakirə etmək","l":[
 ("A","Thank you for the quotation. I have a few questions.","Qiymət təklifi üçün təşəkkür. Bir neçə sualım var."),
 ("B","Of course, go ahead.","Əlbəttə, buyurun."),
 ("A","The licence cost is higher than we expected.","Lisenziya xərci gözlədiyimizdən yüksəkdir."),
 ("B","It reflects the number of users you requested.","Bu, tələb etdiyiniz istifadəçi sayını əks etdirir."),
 ("A","We could start with fewer seats.","Daha az yerlə başlaya bilərik."),
 ("B","That is possible. How many did you have in mind?","Bu mümkündür. Neçəsini nəzərdə tutursunuz?"),
 ("A","Around sixty for the first year.","İlk il üçün təxminən altmış."),
 ("B","I can offer a fifteen percent discount at that volume.","Bu həcmdə on beş faiz endirim təklif edə bilərəm."),
 ("A","What about support? Is it included?","Dəstək necə? Daxildir?"),
 ("B","Standard support is included. Premium is extra.","Standart dəstək daxildir. Premium əlavədir."),
 ("A","Could you send a revised proposal by Friday?","Cüməyə qədər yenilənmiş təklif göndərə bilərsiniz?"),
 ("B","Certainly. You will have it by Thursday.","Əlbəttə. Cümə axşamına qədər sizdə olacaq.")]},

{"t":"İş müsahibəsi","lv":"B2","d":"Təcrübə və bacarıqlardan danışmaq","l":[
 ("A","Thanks for coming in. Tell me about yourself.","Gəldiyiniz üçün təşəkkür. Özünüz haqqında danışın."),
 ("B","I have been working in banking IT for ten years.","On ildir bank İT sahəsində işləyirəm."),
 ("A","What are you responsible for at the moment?","Hazırda nəyə görə məsulsunuz?"),
 ("B","I manage the whole infrastructure and security.","Bütün infrastruktur və təhlükəsizliyi idarə edirəm."),
 ("A","That is a broad role. Do you have a team?","Geniş vəzifədir. Komandanız var?"),
 ("B","A small one. Most of the work I do myself.","Kiçik. İşin çoxunu özüm görürəm."),
 ("A","What would you say is your biggest achievement?","Ən böyük nailiyyətiniz nədir?"),
 ("B","I built our internal platform from scratch.","Daxili platformamızı sıfırdan qurdum."),
 ("A","And your biggest challenge?","Ən böyük çətinliyiniz?"),
 ("B","Balancing regulatory deadlines with daily support.","Tənzimləyici son tarixləri gündəlik dəstəklə balanslaşdırmaq."),
 ("A","Where do you see yourself in five years?","Beş ildən sonra özünüzü harada görürsünüz?"),
 ("B","Leading a larger infrastructure team.","Daha böyük infrastruktur komandasına rəhbərlik edərkən."),
 ("A","Do you have any questions for us?","Bizə sualınız var?"),
 ("B","Yes, how is the team structured?","Bəli, komanda necə qurulub?")]},

{"t":"Kəsintini idarə etmək","lv":"B2","d":"Böhran anında ünsiyyət","l":[
 ("A","We have a production outage. Users cannot log in.","İstehsalatda kəsinti var. İstifadəçilər girə bilmir."),
 ("B","Since when?","Nə vaxtdan?"),
 ("A","It started about fifteen minutes ago.","Təxminən on beş dəqiqə əvvəl başladı."),
 ("B","Have we identified the root cause?","Əsas səbəbi müəyyən etmisiniz?"),
 ("A","Not yet. The database is responding normally.","Hələ yox. Verilənlər bazası normal cavab verir."),
 ("B","What about the authentication service?","Autentifikasiya xidməti necə?"),
 ("A","That is what we are checking now.","Elə indi onu yoxlayırıq."),
 ("B","Keep the business informed every fifteen minutes.","Hər on beş dəqiqədən bir biznesi məlumatlandırın."),
 ("A","Understood. Should we roll back last night's change?","Anlaşıldı. Dünən gecəki dəyişikliyi geri qaytaraq?"),
 ("B","If we find nothing in ten minutes, yes.","On dəqiqədə heç nə tapmasaq, bəli."),
 ("A","Agreed. I will report back shortly.","Razıyam. Tezliklə məlumat verəcəyəm."),
 ("B","Thank you. Stay calm and document everything.","Sağ olun. Sakit olun və hər şeyi qeyd edin.")]},
]
