# -*- coding: utf-8 -*-
"""Qrammatika kursu - B1 ve B2 seviyye (19-32)"""

B1 = [
{"t":"Present Perfect — have done","lv":"B1","s":[
 ("p","Azərbaycan dilində birbaşa qarşılığı yoxdur, ona görə ən çətin mövzudur. Keçmişi indiki ilə bağlayır."),
 ("f","have / has + felin 3-cü forması"),
 ("h","Üç əsas istifadə"),
 ("p","1. Vaxtı deyilməyən keçmiş təcrübə:"),
 ("e","I have worked with FortiGate. ~ FortiGate ilə işləmişəm."),
 ("p","2. Keçmişdə başlayıb indi də davam edən:"),
 ("e","I have worked here since 2015. ~ 2015-dən burada işləyirəm."),
 ("p","3. Nəticəsi indi görünən:"),
 ("e","I have sent the report. ~ Hesabatı göndərmişəm. (indi sizdədir)"),
 ("h","for və since"),
 ("f","for + müddət:  for two years, for ten minutes"),
 ("f","since + başlanğıc nöqtəsi:  since 2015, since Monday"),
 ("h","Zaman sözləri"),
 ("f","already · yet · just · ever · never · so far · recently"),
 ("e","Have you finished yet? ~ Hələ bitirməmisiniz?"),
 ("e","I have just restarted it. ~ Elə indicə yenidən başlatdım."),
 ("x","I have worked here since two years. ~ I have worked here for two years."),
 ("x","I am working here since 2015. ~ I have worked here since 2015."),
 ("w","Bu zamanla dəqiq keçmiş vaxt (yesterday, last week, in 2020) İŞLƏNMİR.")],
 "q":[
 {"q":"I have worked here ___ five years.","o":["since","for","from"],"a":1,"why":"Müddət bildirəndə 'for' işlənir."},
 {"q":"Hansı düzdür?","o":["I have sent it yesterday.","I sent it yesterday.","I have send it yesterday."],"a":1,"why":"'yesterday' ilə Present Perfect işlənmir."},
 {"q":"'Hələ bitirməmisiniz?'","o":["Did you finish yet?","Have you finished yet?","Are you finished yet?"],"a":1,"why":"'yet' Present Perfect ilə işlənir."}]},

{"t":"Present Perfect vs Past Simple","lv":"B1","s":[
 ("p","Bu fərq ingiliscədə ən çox səhv edilən yerdir. Sual sadədir: vaxt deyilir, yoxsa yox?"),
 ("h","Past Simple — vaxt dəqiqdir və bitib"),
 ("e","I sent the report yesterday. ~ Hesabatı dünən göndərdim."),
 ("e","We migrated the server in 2024. ~ Serveri 2024-də köçürdük."),
 ("h","Present Perfect — vaxt deyilmir, nəticə vacibdir"),
 ("e","I have sent the report. ~ Hesabatı göndərmişəm."),
 ("e","We have migrated three servers. ~ Üç server köçürmüşük."),
 ("h","Praktik yoxlama"),
 ("p","Cümlədə 'yesterday, last week, ago, in 2020, then' varsa — Past Simple."),
 ("p","'already, yet, just, ever, never, since, for, so far' varsa — Present Perfect."),
 ("h","Söhbətdə tipik axın"),
 ("e","Have you been to London? ~ Londonda olmusunuz? (təcrübə)"),
 ("e","Yes, I went there in 2019. ~ Bəli, 2019-da getmişəm. (indi vaxt deyilir)"),
 ("x","When have you sent it? ~ When did you send it?"),
 ("w","'When' sualı həmişə Past Simple ilə qurulur, çünki 'when' özü dəqiq vaxt soruşur.")],
 "q":[
 {"q":"___ you ever used Ansible?","o":["Did","Have","Are"],"a":1,"why":"'ever' təcrübə soruşur, Present Perfect lazımdır."},
 {"q":"I ___ the patch last night.","o":["have installed","installed","install"],"a":1,"why":"'last night' dəqiq keçmiş vaxtdır."},
 {"q":"Hansı düzdür?","o":["When have you arrived?","When did you arrive?","When you arrived?"],"a":1,"why":"'When' ilə Past Simple işlənir."}]},

{"t":"Past Continuous — davam edirdi","lv":"B1","s":[
 ("p","Keçmişdə müəyyən anda davam edən hərəkət. Çox vaxt Past Simple ilə birlikdə işlənir."),
 ("f","was / were + fel-ing"),
 ("e","I was working when the power went off. ~ İşıq gedəndə işləyirdim."),
 ("e","They were testing the system all night. ~ Bütün gecə sistemi test edirdilər."),
 ("h","İki hərəkətin birləşməsi"),
 ("p","Uzun hərəkət — Past Continuous. Onu kəsən qısa hərəkət — Past Simple."),
 ("f","while + Past Continuous      ·      when + Past Simple"),
 ("e","While I was checking the logs, the server crashed. ~ Jurnalları yoxlayarkən server çökdü."),
 ("h","Fon təsviri"),
 ("e","It was raining and the network was unstable. ~ Yağış yağırdı və şəbəkə qeyri-sabit idi."),
 ("x","I was knowing the answer. ~ I knew the answer."),
 ("x","While I checked the logs, it crashed. ~ While I was checking the logs, it crashed."),
 ("w","'while' ilə adətən Continuous, 'when' ilə adətən Simple işlənir.")],
 "q":[
 {"q":"I ___ when he called.","o":["worked","was working","have worked"],"a":1,"why":"Zəng gələndə davam edən hərəkət."},
 {"q":"___ I was testing, the disk failed.","o":["When","While","Since"],"a":1,"why":"Davam edən hərəkətlə 'while' işlənir."},
 {"q":"Hansı SƏHVDİR?","o":["I was reading.","I was understanding.","I was writing."],"a":1,"why":"'understand' Continuous formada işlənmir."}]},

{"t":"Past Perfect — keçmişdən əvvəlki keçmiş","lv":"B1","s":[
 ("p","Keçmişdə iki hadisə varsa və biri o birindən əvvəl olubsa, əvvəlki üçün Past Perfect işlənir."),
 ("f","had + felin 3-cü forması  (bütün şəxslər üçün eyni)"),
 ("e","The server had already crashed when I arrived. ~ Mən çatanda server artıq çökmüşdü."),
 ("e","I realised that I had forgotten the password. ~ Şifrəni unutduğumu anladım."),
 ("h","Sıralama"),
 ("p","Əvvəl baş verən = had + 3-cü forma. Sonra baş verən = Past Simple."),
 ("e","He left before I had finished. ~ Mən bitirməmiş o getdi."),
 ("h","Tez-tez işlənən sözlər"),
 ("f","already · just · never · before · after · by the time"),
 ("e","By the time we noticed, the data had been deleted. ~ Biz görəndə məlumat artıq silinmişdi."),
 ("x","When I arrived, the meeting already started. ~ When I arrived, the meeting had already started."),
 ("w","Hadisələr sıra ilə baş veribsə Past Perfect lazım deyil — sadəcə Past Simple kifayətdir.")],
 "q":[
 {"q":"When I arrived, they ___ already left.","o":["have","had","were"],"a":1,"why":"Mən çatmamışdan əvvəl getmişdilər."},
 {"q":"Hansı düzdür?","o":["I had forgot the key.","I had forgotten the key.","I had forgetting the key."],"a":1,"why":"'had' ilə felin 3-cü forması işlənir."},
 {"q":"'Biz görəndə fayl artıq silinmişdi':","o":["...the file was already deleted.","...the file had already been deleted.","...the file has already deleted."],"a":1,"why":"Daha əvvəlki keçmiş + məchul növ."}]},

{"t":"Gerund və Infinitive — -ing yoxsa to","lv":"B1","s":[
 ("p","Bir felin ardınca başqa fel gələndə hansı forma seçilir? Bu, birinci feldən asılıdır və əzbərlənir."),
 ("h","-ing tələb edən fellər"),
 ("f","enjoy · finish · avoid · suggest · consider · practise"),
 ("f","mind · keep · recommend · risk · involve"),
 ("e","I finished writing the script. ~ Skripti yazıb bitirdim."),
 ("e","We avoid using shared accounts. ~ Ümumi hesablardan istifadə etməkdən çəkinirik."),
 ("h","to + fel tələb edənlər"),
 ("f","want · need · decide · plan · hope · agree · offer"),
 ("f","promise · refuse · manage · learn · seem"),
 ("e","We decided to upgrade the firmware. ~ Proqram təminatını yeniləməyə qərar verdik."),
 ("h","Sözönündən sonra HƏMİŞƏ -ing"),
 ("e","Thank you for helping me. ~ Kömək etdiyiniz üçün təşəkkür."),
 ("e","He is good at solving problems. ~ Problem həll etməkdə yaxşıdır."),
 ("h","Məna dəyişənlər"),
 ("e","I stopped smoking. ~ Siqareti tərgitdim."),
 ("e","I stopped to smoke. ~ Siqaret çəkmək üçün dayandım."),
 ("x","I suggest to use SSH. ~ I suggest using SSH."),
 ("x","I am interested in to learn Linux. ~ I am interested in learning Linux."),
 ("w","'to' sözönü olanda da -ing gəlir: 'look forward to hearing from you'.")],
 "q":[
 {"q":"We decided ___ the server.","o":["upgrading","to upgrade","upgrade"],"a":1,"why":"'decide' feldən sonra 'to + fel' gəlir."},
 {"q":"I suggest ___ a stronger password.","o":["to use","using","use"],"a":1,"why":"'suggest' feldən sonra -ing gəlir."},
 {"q":"Thank you for ___ me.","o":["help","to help","helping"],"a":2,"why":"Sözönündən sonra həmişə -ing."}]},

{"t":"Şərt cümlələri — 0 və 1","lv":"B1","s":[
 ("p","Şərt cümlələri 'if' ilə qurulur. Dörd tipi var, ilk ikisi real hallar üçündür."),
 ("h","Tip 0 — həmişə doğru olan"),
 ("f","If + Present Simple, Present Simple"),
 ("e","If you delete the file, it goes to the bin. ~ Faylı silsəniz, səbətə düşür."),
 ("e","If the CPU exceeds 90 percent, the alert fires. ~ Prosessor 90 faizi keçəndə xəbərdarlıq işə düşür."),
 ("h","Tip 1 — real, mümkün gələcək"),
 ("f","If + Present Simple, will + fel"),
 ("e","If you send it today, I will review it tomorrow. ~ Bu gün göndərsəniz, sabah baxaram."),
 ("e","If the test fails, we will roll back. ~ Test uğursuz olsa, geri qaytaracağıq."),
 ("h","Ən vacib qayda"),
 ("p","'if' hissəsində HEÇ VAXT 'will' işlənmir. Bu, 'when', 'as soon as', 'until', 'before', 'after' üçün də keçərlidir."),
 ("x","If it will fail, we will roll back. ~ If it fails, we will roll back."),
 ("x","When I will finish, I will call. ~ When I finish, I will call."),
 ("h","unless = if not"),
 ("e","Unless you confirm, we will cancel it. ~ Təsdiqləməsəniz, ləğv edəcəyik.")],
 "q":[
 {"q":"If the backup ___, we will restore it.","o":["will work","works","worked"],"a":1,"why":"'if' hissəsində gələcək zaman işlənmir."},
 {"q":"Hansı düzdür?","o":["When I will arrive, I will call.","When I arrive, I will call.","When I arrive, I call."],"a":1,"why":"'when' sonra indiki, əsas hissədə 'will'."},
 {"q":"'Təsdiqləməsəniz, ləğv edəcəyik':","o":["Unless you confirm, we will cancel.","If you confirm, we will cancel.","Unless you will confirm, we cancel."],"a":0,"why":"'unless' = 'if not'."}]},

{"t":"Şərt cümlələri — 2 və 3","lv":"B1","s":[
 ("p","Bu iki tip real olmayan, xəyali vəziyyətlər üçündür."),
 ("h","Tip 2 — indiki qeyri-real"),
 ("f","If + Past Simple, would + fel"),
 ("e","If I had more budget, I would buy a new firewall. ~ Daha çox büdcəm olsaydı, yeni firewall alardım."),
 ("e","If I were you, I would enable 2FA. ~ Sənin yerinə olsaydım, ikifaktorlu təsdiqi aktiv edərdim."),
 ("p","Diqqət: bu tipdə bütün şəxslərlə 'were' işlənir — 'If I were', 'If he were'."),
 ("h","Tip 3 — keçmiş qeyri-real, peşmançılıq"),
 ("f","If + had + 3-cü forma, would have + 3-cü forma"),
 ("e","If we had tested it, the outage would not have happened. ~ Test etsəydik, kəsinti olmazdı."),
 ("e","If I had known, I would have called you. ~ Bilsəydim, sizə zəng edərdim."),
 ("h","Yadda saxlamaq üçün sadə cədvəl"),
 ("f","Tip 1:  if + indiki  →  will"),
 ("f","Tip 2:  if + keçmiş  →  would"),
 ("f","Tip 3:  if + had done  →  would have done"),
 ("x","If I would have money... ~ If I had money..."),
 ("w","'if' hissəsində heç vaxt 'would' işlənmir.")],
 "q":[
 {"q":"If I ___ you, I would not click that link.","o":["am","was","were"],"a":2,"why":"Tip 2-də 'If I were' işlənir."},
 {"q":"If we had tested it, it ___ failed.","o":["would not have","would not","will not have"],"a":0,"why":"Tip 3: would have + 3-cü forma."},
 {"q":"Hansı SƏHVDİR?","o":["If I had time, I would help.","If I would have time, I would help.","If I have time, I will help."],"a":1,"why":"'if' hissəsində 'would' olmaz."}]},

{"t":"Məchul növ — Passive Voice","lv":"B1","s":[
 ("p","İşi kimin gördüyü məlum deyilsə və ya vacib deyilsə işlənir. Texniki və rəsmi mətnlərdə çox rast gəlinir."),
 ("f","to be + felin 3-cü forması"),
 ("h","Zamanlara görə"),
 ("f","Present:  The file is checked daily."),
 ("f","Past:  The server was restarted."),
 ("f","Present Perfect:  The patch has been installed."),
 ("f","Future:  The report will be sent."),
 ("f","Modal:  Access must be revoked."),
 ("e","The system was hacked last year. ~ Sistem keçən il sındırıldı."),
 ("e","Logs are stored for one year. ~ Jurnallar bir il saxlanılır."),
 ("h","by — icraçını göstərmək"),
 ("e","The report was prepared by the IT department. ~ Hesabat İT şöbəsi tərəfindən hazırlandı."),
 ("h","Nə vaxt işlətməli"),
 ("p","Rəsmi yazışmada, prosedurlarda, hesabatlarda. Gündəlik danışıqda az işlənir."),
 ("x","The file was delete. ~ The file was deleted."),
 ("x","The system is hack. ~ The system was hacked."),
 ("w","'to be' hissəsi mütləq lazımdır. Təkcə 3-cü forma kifayət deyil.")],
 "q":[
 {"q":"The patch ___ last night.","o":["was installed","was install","is installing"],"a":0,"why":"Keçmiş məchul: was + 3-cü forma."},
 {"q":"Access must ___ immediately.","o":["be revoked","revoked","is revoked"],"a":0,"why":"Modaldan sonra 'be + 3-cü forma'."},
 {"q":"'Jurnallar bir il saxlanılır':","o":["Logs store for one year.","Logs are stored for one year.","Logs are storing for one year."],"a":1,"why":"Məchul növ: are + stored."}]},
]

B2 = [
{"t":"Relative clauses — who, which, that","lv":"B2","s":[
 ("p","İsim haqqında əlavə məlumat vermək üçün. Azərbaycan dilində bunu -an/-ən şəkilçisi edir."),
 ("f","who — insan   ·   which — əşya   ·   that — hər ikisi"),
 ("f","where — yer   ·   whose — yiyəlik   ·   when — vaxt"),
 ("e","The engineer who fixed it is on leave. ~ Onu düzəldən mühəndis məzuniyyətdədir."),
 ("e","The server which crashed is old. ~ Çökən server köhnədir."),
 ("h","İki növ"),
 ("p","1. Zəruri (vergülsüz) — məlumat olmadan cümlə anlaşılmır:"),
 ("e","The file that I sent is encrypted. ~ Göndərdiyim fayl şifrələnib."),
 ("p","2. Əlavə (vergüllü) — sadəcə əlavə məlumat:"),
 ("e","Our server, which we bought in 2020, is slow. ~ 2020-də aldığımız serverimiz yavaşdır."),
 ("w","Vergüllü variantda 'that' İŞLƏNMİR — yalnız 'who' və ya 'which'."),
 ("h","Buraxıla bilən hallar"),
 ("p","Əgər əvəzlik tamamlıqdırsa, onu buraxmaq olar:"),
 ("e","The file I sent is encrypted. ~ Göndərdiyim fayl şifrələnib."),
 ("x","The engineer which fixed it. ~ The engineer who fixed it."),
 ("x","The man what called you. ~ The man who called you."),
 ("w","'what' relative pronoun kimi işlənmir. Yalnız who / which / that.")],
 "q":[
 {"q":"The user ___ reported the bug is offline.","o":["which","who","what"],"a":1,"why":"İnsan üçün 'who' işlənir."},
 {"q":"Hansı düzdür?","o":["Our server, that is old, failed.","Our server, which is old, failed.","Our server what is old failed."],"a":1,"why":"Vergüllü əlavə cümlədə 'that' işlənmir."},
 {"q":"Hansı variantda əvəzliyi buraxmaq OLAR?","o":["The man who called me.","The file that I sent.","The tool which crashed."],"a":1,"why":"'I sent' — əvəzlik tamamlıqdır, buraxıla bilər."}]},

{"t":"Dolayı nitq — Reported Speech","lv":"B2","s":[
 ("p","Başqasının sözünü çatdırmaq üçün. Zaman bir pillə geri çəkilir."),
 ("h","Zaman dəyişməsi"),
 ("f","present → past:  works → worked"),
 ("f","past → past perfect:  worked → had worked"),
 ("f","will → would   ·   can → could   ·   must → had to"),
 ("e","He said: 'I am busy.' ~ He said he was busy."),
 ("e","She said: 'I will send it.' ~ She said she would send it."),
 ("h","Digər dəyişikliklər"),
 ("f","today → that day   ·   tomorrow → the next day"),
 ("f","yesterday → the day before   ·   now → then"),
 ("f","this → that   ·   here → there"),
 ("h","Sualların çatdırılması"),
 ("p","Söz sırası NORMAL olur, köməkçi fel qalxmır."),
 ("e","He asked: 'Where is the file?' ~ He asked where the file was."),
 ("e","She asked: 'Did you send it?' ~ She asked if I had sent it."),
 ("h","say və tell"),
 ("f","say + söz:  He said that..."),
 ("f","tell + kimə + söz:  He told me that..."),
 ("x","He said me that... ~ He told me that..."),
 ("x","He asked where is the server. ~ He asked where the server was."),
 ("w","Bəli/xeyr sualı çatdırılanda 'if' və ya 'whether' işlənir.")],
 "q":[
 {"q":"He said: 'I am ready.' Dolayı forma:","o":["He said he is ready.","He said he was ready.","He said he were ready."],"a":1,"why":"Present → Past keçir."},
 {"q":"Hansı düzdür?","o":["He said me the news.","He told me the news.","He told to me the news."],"a":1,"why":"'tell' birbaşa şəxs alır, 'say' almır."},
 {"q":"She asked: 'Did you finish?'","o":["She asked did I finish.","She asked if I had finished.","She asked if did I finish."],"a":1,"why":"Bəli/xeyr sualı 'if' ilə, söz sırası normal."}]},

{"t":"Modal perfect — should have, must have","lv":"B2","s":[
 ("p","Keçmiş haqqında fikir, təxmin və peşmançılıq bildirir. Rəsmi danışıqda çox işlənir."),
 ("f","modal + have + felin 3-cü forması"),
 ("h","should have — etməli idin, amma etmədin"),
 ("e","We should have tested it first. ~ Əvvəlcə test etməli idik."),
 ("e","You shouldn't have shared the key. ~ Açarı paylaşmamalı idiniz."),
 ("h","must have — güclü təxmin, əmin olma"),
 ("e","The disk must have failed overnight. ~ Disk yəqin gecə sıradan çıxıb."),
 ("h","might / may have — zəif ehtimal"),
 ("e","Someone might have changed the config. ~ Kimsə konfiqurasiyanı dəyişmiş ola bilər."),
 ("h","can't have — mümkün deyil"),
 ("e","He can't have deleted it, he has no access. ~ O silə bilməzdi, girişi yoxdur."),
 ("h","could have — mümkün idi, amma olmadı"),
 ("e","We could have avoided the outage. ~ Kəsintinin qarşısını ala bilərdik."),
 ("x","I should have went. ~ I should have gone."),
 ("x","It must has failed. ~ It must have failed."),
 ("w","'have' heç vaxt dəyişmir — 'has' yox, həmişə 'have'.")],
 "q":[
 {"q":"'Əvvəlcə test etməli idik':","o":["We should test it first.","We should have tested it first.","We must test it first."],"a":1,"why":"Keçmişdəki peşmançılıq: should have + 3-cü forma."},
 {"q":"Hansı düzdür?","o":["It must has failed.","It must have failed.","It must had failed."],"a":1,"why":"Modaldan sonra həmişə 'have'."},
 {"q":"'Silə bilməzdi' (mümkünsüz):","o":["He mustn't have deleted it.","He can't have deleted it.","He shouldn't have deleted it."],"a":1,"why":"Mümkünsüzlük üçün 'can't have'."}]},

{"t":"Phrasal verb quruluşu","lv":"B2","s":[
 ("p","Fel + sözönü birləşməsi. Mənası çox vaxt tərkib hissələrindən çıxmır — əzbərlənir."),
 ("h","Ayrıla bilənlər"),
 ("p","Tamamlıq ortada da, sonda da dura bilər:"),
 ("e","Turn off the server. / Turn the server off. ~ Serveri söndür."),
 ("p","AMMA əvəzlik olsa MÜTLƏQ ortada durur:"),
 ("e","Turn it off. ~ Onu söndür."),
 ("x","Turn off it. ~ Turn it off."),
 ("h","Ayrılmayanlar"),
 ("p","Tamamlıq həmişə sonda gəlir:"),
 ("e","I am looking for the file. ~ Faylı axtarıram."),
 ("x","I am looking the file for. ~ I am looking for the file."),
 ("h","İşdə ən çox lazım olanlar"),
 ("f","set up — qurmaq   ·   back up — nüsxə çıxarmaq"),
 ("f","shut down — söndürmək   ·   log in / out — girmək / çıxmaq"),
 ("f","figure out — başa düşmək   ·   carry out — həyata keçirmək"),
 ("f","follow up — təqib etmək   ·   come up with — irəli sürmək"),
 ("f","run out of — tükənmək   ·   deal with — məşğul olmaq"),
 ("w","Rəsmi yazışmada bəzən tək sözlü qarşılıq daha uyğundur: 'carry out' əvəzinə 'conduct', 'find out' əvəzinə 'determine'.")],
 "q":[
 {"q":"Hansı düzdür?","o":["Turn off it.","Turn it off.","It turn off."],"a":1,"why":"Əvəzlik həmişə felin ortasında durur."},
 {"q":"'Faylı axtarıram':","o":["I am looking the file for.","I am looking for the file.","I am for looking the file."],"a":1,"why":"'look for' ayrılmayan phrasal verb-dir."},
 {"q":"'Ehtiyat nüsxə çıxar':","o":["Back up the database.","Back the database up.","Hər ikisi düzdür."],"a":2,"why":"'back up' ayrıla bilir, isim hər iki yerdə dura bilər."}]},

{"t":"Söz sırası və zərflərin yeri","lv":"B2","s":[
 ("p","İngilis cümləsində söz sırası sərtdir. Azərbaycan dilindən tərcümə edəndə ən çox burada səhv edilir."),
 ("f","MÜBTƏDA + FEL + TAMAMLIQ + TƏRZ + YER + ZAMAN"),
 ("e","I sent the report quickly to the manager yesterday. ~ Hesabatı dünən tez menecerə göndərdim."),
 ("h","Tezlik zərflərinin yeri"),
 ("p","always, usually, often, sometimes, never, already — əsas feldən ƏVVƏL:"),
 ("e","I always check the logs. ~ Həmişə jurnalları yoxlayıram."),
 ("p","AMMA 'to be' felindən SONRA:"),
 ("e","He is always late. ~ O həmişə gecikir."),
 ("p","Köməkçi fel varsa — onunla əsas felin ARASINDA:"),
 ("e","I have never seen this error. ~ Bu xətanı heç vaxt görməmişəm."),
 ("h","Sifətlərin sırası"),
 ("f","fikir → ölçü → yaş → forma → rəng → mənşə → material"),
 ("e","a small old black metal box ~ kiçik köhnə qara metal qutu"),
 ("h","Tamamlıq feldən ayrılmır"),
 ("x","I like very much this tool. ~ I like this tool very much."),
 ("x","I speak very well English. ~ I speak English very well."),
 ("w","Fel ilə tamamlığın arasına zərf girmir. Bu, ana dilimizdən gələn ən tez-tez rast gəlinən səhvdir.")],
 "q":[
 {"q":"Hansı düzdür?","o":["I like very much it.","I like it very much.","I very much like it."],"a":1,"why":"Fel ilə tamamlıq arasına zərf girmir."},
 {"q":"'Heç vaxt görməmişəm':","o":["I never have seen it.","I have never seen it.","I have seen never it."],"a":1,"why":"Zərf köməkçi ilə əsas felin arasında durur."},
 {"q":"He ___ late.","o":["always is","is always","always"],"a":1,"why":"'to be' felindən sonra gəlir."}]},

{"t":"Azərbaycanlıların ən çox etdiyi 15 səhv","lv":"B2","s":[
 ("p","Bu siyahını vaxtaşırı oxu. Səhvlərin çoxu ana dilinin təsirindən yaranır."),
 ("x","I am agree. ~ I agree."),
 ("x","I have 30 years old. ~ I am 30 years old."),
 ("x","I am working here since 2015. ~ I have worked here since 2015."),
 ("x","Where you are going? ~ Where are you going?"),
 ("x","He don't know. ~ He doesn't know."),
 ("x","I didn't went there. ~ I didn't go there."),
 ("x","Explain me this. ~ Explain this to me."),
 ("x","I am interested about it. ~ I am interested in it."),
 ("x","Every peoples know. ~ Everyone knows."),
 ("x","Two informations. ~ Two pieces of information."),
 ("x","I will call you when I will arrive. ~ I will call you when I arrive."),
 ("x","It depends of the load. ~ It depends on the load."),
 ("x","I am boring in this meeting. ~ I am bored in this meeting."),
 ("x","Thanks God. ~ Thank God."),
 ("x","In my opinion I think... ~ In my opinion... / I think..."),
 ("h","Bir neçə qeyd"),
 ("p","'boring' = darıxdırıcı (əşya). 'bored' = darıxmış (insan). Eyni qayda: interesting / interested, tiring / tired."),
 ("p","'agree' felin özüdür — 'be' lazım deyil."),
 ("p","Yaş həmişə 'be' ilə deyilir: I am 30, he is 45."),
 ("w","Bu 15 səhvi düzəltsən, ingiliscən dərhal daha təbii səslənəcək.")],
 "q":[
 {"q":"Hansı düzdür?","o":["I am agree with you.","I agree with you.","I am agreeing with you."],"a":1,"why":"'agree' feldir, 'be' ilə işlənmir."},
 {"q":"'30 yaşım var':","o":["I have 30 years.","I am 30 years old.","I am 30 years."],"a":1,"why":"İngiliscədə yaş 'be' feli ilə deyilir."},
 {"q":"'Bu iclasda darıxıram':","o":["I am boring.","I am bored.","I am bore."],"a":1,"why":"İnsan üçün 'bored', əşya üçün 'boring'."}]},
]
