# -*- coding: utf-8 -*-
"""Qrammatika kursu - A2 seviyye (11-18)"""

A2 = [
{"t":"Present Continuous — indi baş verən","lv":"A2","s":[
 ("p","Danışıq anında davam edən hərəkət üçün. Azərbaycan dilində 'edirəm' formasına yaxındır."),
 ("f","am / is / are + fel-ing"),
 ("e","I am working on the report now. ~ İndi hesabat üzərində işləyirəm."),
 ("e","The server is restarting. ~ Server yenidən başlayır."),
 ("h","-ing yazılış qaydası"),
 ("f","adi:  work → working"),
 ("f","sonda 'e' düşür:  make → making, use → using"),
 ("f","tək saitli qısa fel — son samit ikiləşir:  run → running, put → putting"),
 ("h","Yaxın gələcək üçün də işlənir"),
 ("e","I am meeting the vendor tomorrow. ~ Sabah təchizatçı ilə görüşürəm."),
 ("h","Bu fellər Continuous-da İŞLƏNMİR"),
 ("f","know · understand · like · want · need · believe · belong · seem"),
 ("x","I am knowing the answer. ~ I know the answer."),
 ("x","He working now. ~ He is working now."),
 ("w","'am/is/are' hissəsini unutma. Təkcə -ing kifayət deyil.")],
 "q":[
 {"q":"He ___ the logs right now.","o":["checks","is checking","check"],"a":1,"why":"'right now' indi davam edən hərəkəti bildirir."},
 {"q":"Hansı SƏHVDİR?","o":["I am waiting.","I am understanding.","I am reading."],"a":1,"why":"'understand' Continuous-da işlənmir."},
 {"q":"'run' felinin -ing forması:","o":["runing","running","runnning"],"a":1,"why":"Tək saitli qısa feldə son samit ikiləşir."}]},

{"t":"Present Simple vs Continuous","lv":"A2","s":[
 ("p","Bu iki zamanı qarışdırmaq ən çox rast gəlinən səhvdir. Fərq sadədir: adət yoxsa indi?"),
 ("h","Present Simple — adət, qayda, həmişəlik"),
 ("e","I work at a bank. ~ Bankda işləyirəm. (daimi)"),
 ("e","The system runs every night. ~ Sistem hər gecə işləyir."),
 ("h","Present Continuous — indi, müvəqqəti"),
 ("e","I am working on a migration. ~ Miqrasiya üzərində işləyirəm. (bu dövr)"),
 ("e","The system is running now. ~ Sistem indi işləyir."),
 ("h","Yardımçı sözlər"),
 ("f","Simple:  always · usually · every day · often · never"),
 ("f","Continuous:  now · at the moment · today · this week · currently"),
 ("h","Məna dəyişən nümunə"),
 ("e","I see the problem. ~ Problemi görürəm. (anlayıram)"),
 ("e","I am seeing the client. ~ Müştəri ilə görüşürəm."),
 ("x","I am working here since 2015. ~ I have worked here since 2015."),
 ("w","Nə vaxtdan bəri davam edir deyəndə Present Perfect lazımdır, Continuous yox.")],
 "q":[
 {"q":"I usually ___ at eight.","o":["start","am starting","starting"],"a":0,"why":"'usually' adəti bildirir, Present Simple lazımdır."},
 {"q":"Look! The server ___ down.","o":["goes","is going","go"],"a":1,"why":"'Look!' indi baş verəni bildirir."},
 {"q":"Hansı düzdür?","o":["I am knowing him.","I know him.","I knowing him."],"a":1,"why":"'know' Continuous-da işlənmir."}]},

{"t":"Past Simple — düzgün fellər","lv":"A2","s":[
 ("p","Keçmişdə bitmiş hərəkət üçün. Vaxtı dəqiq bilinən və ya bilinməsi vacib olan hallarda."),
 ("f","fel + ed  (bütün şəxslər üçün eyni)"),
 ("e","I finished the report yesterday. ~ Hesabatı dünən bitirdim."),
 ("e","They installed the patch last night. ~ Yamağı dünən gecə qurdular."),
 ("h","-ed yazılış qaydası"),
 ("f","adi:  work → worked"),
 ("f","sonda 'e' varsa yalnız -d:  use → used"),
 ("f","samit + y:  apply → applied"),
 ("f","qısa fel, son samit ikiləşir:  stop → stopped, plan → planned"),
 ("h","İnkar və sual — did"),
 ("f","İnkar:  did not (didn't) + sadə fel"),
 ("f","Sual:  Did + mübtəda + sadə fel?"),
 ("e","Did you send the file? ~ Faylı göndərdiniz?"),
 ("e","I didn't receive it. ~ Almadım."),
 ("h","Zaman sözləri"),
 ("f","yesterday · last week · two days ago · in 2020 · then"),
 ("x","I didn't finished it. ~ I didn't finish it."),
 ("x","Did he sent it? ~ Did he send it?"),
 ("w","'did' varsa əsas feldə -ed OLMUR. Keçmişlik artıq 'did' sözündədir.")],
 "q":[
 {"q":"Hansı düzdür?","o":["Did you sent it?","Did you send it?","Did you sending it?"],"a":1,"why":"'did' varsa fel sadə formada qalır."},
 {"q":"'stop' felinin keçmiş forması:","o":["stoped","stopped","stopt"],"a":1,"why":"Qısa feldə son samit ikiləşir."},
 {"q":"'Dünən qurdum':","o":["I install it yesterday.","I installed it yesterday.","I have installed it yesterday."],"a":1,"why":"'yesterday' dəqiq keçmiş vaxtdır, Past Simple lazımdır."}]},

{"t":"Past Simple — nizamsız fellər","lv":"A2","s":[
 ("p","Ən çox işlənən fellərin əksəriyyəti nizamsızdır. Onları əzbərləmək lazımdır — qayda yoxdur."),
 ("h","Ən vacib 20-si"),
 ("f","be → was/were   ·   have → had   ·   do → did"),
 ("f","go → went   ·   come → came   ·   see → saw"),
 ("f","get → got   ·   give → gave   ·   take → took"),
 ("f","make → made   ·   say → said   ·   tell → told"),
 ("f","know → knew   ·   think → thought   ·   find → found"),
 ("f","send → sent   ·   write → wrote   ·   read → read"),
 ("f","run → ran   ·   put → put   ·   break → broke"),
 ("e","I sent the file, but he didn't read it. ~ Faylı göndərdim, amma o oxumadı."),
 ("h","Diqqət"),
 ("p","'read' yazılışı dəyişmir, amma tələffüz dəyişir: rid (indiki) → red (keçmiş)."),
 ("p","was — I, he, she, it ilə. were — you, we, they ilə."),
 ("x","I goed to Baku. ~ I went to Baku."),
 ("x","We was there. ~ We were there."),
 ("w","Proqramda 'Nizamsız fellər' paketi var — orada 100 felin hər üç forması yazılıb.")],
 "q":[
 {"q":"'go' felinin keçmiş forması:","o":["goed","went","gone"],"a":1,"why":"'gone' üçüncü formadır, keçmiş zaman 'went'."},
 {"q":"We ___ at the office.","o":["was","were","been"],"a":1,"why":"'we' ilə 'were' işlənir."},
 {"q":"Hansı düzdür?","o":["He sended it.","He sent it.","He did sent it."],"a":1,"why":"'send' nizamsızdır: send → sent → sent."}]},

{"t":"Gələcək — will və going to","lv":"A2","s":[
 ("p","İngiliscədə gələcək üçün bir neçə forma var. Fərqi bilmək vacibdir."),
 ("h","will — indi qərar verilən, proqnoz, vəd"),
 ("f","will + sadə fel  (bütün şəxslər üçün eyni)"),
 ("e","I will check it now. ~ İndi yoxlayacağam. (elə indi qərar verdim)"),
 ("e","It will rain tomorrow. ~ Sabah yağış yağacaq. (proqnoz)"),
 ("e","I will send it by Friday. ~ Cüməyə qədər göndərəcəyəm. (vəd)"),
 ("h","going to — əvvəlcədən planlaşdırılmış"),
 ("f","am / is / are + going to + sadə fel"),
 ("e","We are going to migrate the server on Sunday. ~ Bazar günü serveri köçürəcəyik. (plan var)"),
 ("e","Look at the disk — it is going to fill up. ~ Diskə bax, dolacaq. (əlamət var)"),
 ("h","Present Continuous — razılaşdırılmış görüş"),
 ("e","I am meeting the auditor at three. ~ Saat üçdə auditorla görüşürəm."),
 ("x","I will to help you. ~ I will help you."),
 ("x","When I will finish, I will call you. ~ When I finish, I will call you."),
 ("w","Çox vacib: 'when', 'if', 'after', 'before', 'as soon as' sözlərindən sonra gələcək zaman İŞLƏNMİR — indiki zaman işlənir.")],
 "q":[
 {"q":"We ___ migrate the server on Sunday. (plan hazırdır)","o":["will","are going to","go to"],"a":1,"why":"Əvvəlcədən qurulmuş plan üçün 'going to'."},
 {"q":"Hansı düzdür?","o":["If it will fail, call me.","If it fails, call me.","If it failing, call me."],"a":1,"why":"'if' sonra gələcək zaman işlənmir."},
 {"q":"Telefon zəng çalır: 'I ___ answer it.'","o":["will","am going to","going to"],"a":0,"why":"Elə indi qəbul edilən qərar üçün 'will'."}]},

{"t":"Müqayisə dərəcələri","lv":"A2","s":[
 ("p","İki şeyi müqayisə etmək və ən üstünü bildirmək üçün. Qayda sözün uzunluğundan asılıdır."),
 ("h","Qısa sifətlər (1 heca)"),
 ("f","fast → faster → the fastest"),
 ("f","big → bigger → the biggest  (son samit ikiləşir)"),
 ("f","easy → easier → the easiest  (y düşür)"),
 ("h","Uzun sifətlər (2+ heca)"),
 ("f","expensive → more expensive → the most expensive"),
 ("f","important → more important → the most important"),
 ("h","Nizamsızlar"),
 ("f","good → better → the best"),
 ("f","bad → worse → the worst"),
 ("f","far → further → the furthest"),
 ("h","Cümlədə istifadə"),
 ("e","This server is faster than the old one. ~ Bu server köhnəsindən sürətlidir."),
 ("e","It is the most secure option. ~ Bu ən təhlükəsiz variantdır."),
 ("e","SSD is not as slow as HDD. ~ SSD HDD qədər yavaş deyil."),
 ("x","This is more faster. ~ This is faster."),
 ("x","It is more better. ~ It is better."),
 ("w","'more' və '-er' eyni vaxtda işlənmir. Biri kifayətdir.")],
 "q":[
 {"q":"This option is ___ than that one.","o":["more cheap","cheaper","most cheap"],"a":1,"why":"'cheap' qısa sifətdir, -er alır."},
 {"q":"Hansı düzdür?","o":["It is more better.","It is better.","It is the more good."],"a":1,"why":"'good' nizamsızdır: good → better → best."},
 {"q":"'ən vacib':","o":["the importantest","the most important","the more important"],"a":1,"why":"Uzun sifətlə 'the most' işlənir."}]},

{"t":"Sayılan / sayılmayan — much, many, some, any","lv":"A2","s":[
 ("p","İngiliscədə isimlər iki qrupa bölünür və bu, hansı sözlə işlənəcəyini müəyyən edir."),
 ("f","Sayılan:  file, server, user, report  (cəm ola bilir)"),
 ("f","Sayılmayan:  water, money, time, information, software, advice"),
 ("h","Miqdar sözləri"),
 ("f","many + sayılan cəm:  many users"),
 ("f","much + sayılmayan:  much time"),
 ("f","a lot of + hər ikisi:  a lot of users / a lot of time"),
 ("f","a few + sayılan:  a few minutes"),
 ("f","a little + sayılmayan:  a little water"),
 ("h","some və any"),
 ("f","some — təsdiq cümlədə:  I have some questions."),
 ("f","any — inkar və sualda:  Do you have any questions?"),
 ("p","İstisna: təklif və xahişdə 'some' işlənir — 'Would you like some tea?'"),
 ("e","We do not have much time, but there are a few options. ~ Çox vaxtımız yoxdur, amma bir neçə variant var."),
 ("x","How much users? ~ How many users?"),
 ("x","I need some informations. ~ I need some information."),
 ("w","'many' sayıla bilənlə, 'much' sayılmayanla. Sualda çox vaxt 'how many / how much' işlənir.")],
 "q":[
 {"q":"How ___ users are online?","o":["much","many","a lot"],"a":1,"why":"'users' sayıla biləndir, 'many' işlənir."},
 {"q":"We do not have ___ time.","o":["many","much","few"],"a":1,"why":"'time' sayılmayandır, 'much' işlənir."},
 {"q":"Do you have ___ questions?","o":["some","any","much"],"a":1,"why":"Sual cümləsində 'any' işlənir."}]},

{"t":"Modal fellər — must, should, have to","lv":"A2","s":[
 ("p","Məcburiyyət, məsləhət və zərurət bildirir. Fərqləri incədir, amma vacibdir."),
 ("h","must — güclü daxili məcburiyyət, qayda"),
 ("e","You must change your password every 90 days. ~ Şifrəni hər 90 gündən bir dəyişməlisiniz."),
 ("h","have to — xarici məcburiyyət, şərait"),
 ("e","I have to work on Saturday. ~ Şənbə işləməli oluram."),
 ("h","should — məsləhət, tövsiyə"),
 ("e","You should enable two-factor authentication. ~ İkifaktorlu autentifikasiyanı aktiv etməlisiniz."),
 ("h","İnkarda MƏNA TAM DƏYİŞİR"),
 ("f","must not = qadağandır"),
 ("f","do not have to = lazım deyil, məcbur deyilsən"),
 ("e","You mustn't share the password. ~ Şifrəni paylaşmaq qadağandır."),
 ("e","You don't have to come early. ~ Erkən gəlmək məcburi deyil."),
 ("h","Keçmiş forma"),
 ("f","must → had to      ·      should → should have + 3-cü forma"),
 ("e","I had to restart it. ~ Yenidən başlatmalı oldum."),
 ("x","I must to go. ~ I must go."),
 ("x","He musts follow the rule. ~ He must follow the rule."),
 ("w","'must not' və 'don't have to' arasındakı fərqi qarışdırmaq ciddi anlaşılmazlığa səbəb olur.")],
 "q":[
 {"q":"'Şifrəni paylaşmaq qadağandır':","o":["You don't have to share it.","You mustn't share it.","You shouldn't have shared it."],"a":1,"why":"Qadağa üçün 'must not' işlənir."},
 {"q":"Hansı düzdür?","o":["I must to go now.","I must go now.","I must going now."],"a":1,"why":"Modaldan sonra 'to' işlənmir."},
 {"q":"Məsləhət vermək üçün ən uyğunu:","o":["You must use a VPN.","You should use a VPN.","You have to use a VPN."],"a":1,"why":"'should' tövsiyə bildirir."}]},
]
