# -*- coding: utf-8 -*-
"""Qrammatika kursu - A1 seviyye (1-10)
Bolme tipleri:  h=basliq  p=abzas  f=dustur  e=numune(EN ~ AZ)  x=sehv/duz  w=xeberdarliq
"""

A1 = [
{"t":"To be — am / is / are","lv":"A1","s":[
 ("p","Azərbaycan dilində 'Mən müəllatəyəm' deyəndə ayrıca fel işlətmirik. İngiliscədə isə HƏR cümlədə fel olmalıdır. 'To be' ən vacib feldir."),
 ("f","I am   ·   he / she / it is   ·   you / we / they are"),
 ("e","I am an engineer. ~ Mən mühəndisəm."),
 ("e","She is at work. ~ O işdədir."),
 ("e","They are ready. ~ Onlar hazırdır."),
 ("h","Qısa formalar"),
 ("f","I am = I'm   ·   he is = he's   ·   they are = they're"),
 ("p","Danışıqda demək olar ki, həmişə qısa forma işlədilir."),
 ("h","İnkar və sual"),
 ("f","İnkar:  I am not  ·  he is not (isn't)  ·  they are not (aren't)"),
 ("f","Sual:  Am I...?  ·  Is he...?  ·  Are they...?"),
 ("e","Is she your manager? ~ O sizin menecerdir?"),
 ("x","I engineer. ~ I am an engineer."),
 ("x","She no ready. ~ She is not ready."),
 ("w","Ən çox edilən səhv: feli tamamilə unutmaq. 'He busy' yox, 'He IS busy'.")],
 "q":[
 {"q":"Düzgün variantı seç: ___ tired.","o":["I am","I is","I are"],"a":0,"why":"'I' ilə həmişə 'am' işlənir."},
 {"q":"'Onlar bankdadır' necə deyilir?","o":["They is at the bank.","They are at the bank.","They at the bank."],"a":1,"why":"'They' cəmdir, ona görə 'are'."},
 {"q":"Sual formasını seç:","o":["She is ready?","Is she ready?","Does she ready?"],"a":1,"why":"'To be' ilə sualda fel qabağa keçir: Is she...?"}]},

{"t":"Artikllar — a / an / the","lv":"A1","s":[
 ("p","Azərbaycan dilində artikl yoxdur, ona görə bu mövzu bizim üçün ən çətinlərdəndir. Amma qayda sadədir."),
 ("h","a / an — qeyri-müəyyən"),
 ("p","İlk dəfə haqqında danışılan, hansı olduğu bilinməyən TƏK sayıla bilən isimlə işlənir."),
 ("f","a + samitlə başlayan söz   ·   an + saitlə başlayan söz (a, e, i, o, u)"),
 ("e","I need a laptop. ~ Mənə noutbuk lazımdır. (hansısa biri)"),
 ("e","She is an engineer. ~ O mühəndisdir."),
 ("w","Vacib: səsə görə seçilir, hərfə görə yox. 'an hour' (saat səssizdir), amma 'a university' (yu- səsi ilə başlayır)."),
 ("h","the — müəyyən"),
 ("p","Hər iki tərəfin bildiyi konkret şey haqqında danışanda işlənir."),
 ("e","The server is down. ~ Server işləmir. (bizim serverimiz)"),
 ("e","I bought a car. The car is red. ~ Maşın aldım. Maşın qırmızıdır."),
 ("h","Artikl işlənmir"),
 ("p","Cəm və ümumi mənada: I like books. Sayılmayan: Water is free. Ölkə, şəhər adları: I live in Baku."),
 ("x","I am engineer. ~ I am an engineer."),
 ("x","I go to the work. ~ I go to work."),
 ("w","'go to work', 'go home', 'at school' — bu ifadələrdə artikl işlənmir. Əzbərlə.")],
 "q":[
 {"q":"___ hour is enough.","o":["A","An","The"],"a":1,"why":"'hour' sözündə h oxunmur, sait səsi ilə başlayır."},
 {"q":"'Server işləmir' (bizim server):","o":["A server is down.","The server is down.","Server is down."],"a":1,"why":"Konkret, hər ikimizin bildiyi server — 'the'."},
 {"q":"Hansı düzdür?","o":["I am a manager.","I am manager.","I am the manager of nothing."],"a":0,"why":"Peşə deyəndə tək isimlə 'a/an' işlənir."}]},

{"t":"Cəm isimlər","lv":"A1","s":[
 ("p","Azərbaycan dilində cəm şəkilçisi -lar/-lər. İngiliscədə əsasən -s əlavə olunur, amma bir neçə istisna var."),
 ("f","adi hal:  file → files   ·   server → servers"),
 ("f","-s, -ss, -sh, -ch, -x, -o sonluqlarda:  +es   ·   box → boxes"),
 ("f","samit + y:  y düşür, +ies   ·   company → companies"),
 ("f","-f / -fe:  → -ves   ·   knife → knives"),
 ("h","Nizamsız cəmlər — əzbərlənir"),
 ("f","man → men  ·  woman → women  ·  child → children"),
 ("f","foot → feet  ·  tooth → teeth  ·  person → people"),
 ("f","dəyişməyənlər:  fish, sheep, information, equipment"),
 ("x","I have three childs. ~ I have three children."),
 ("x","Two informations. ~ Two pieces of information."),
 ("w","'information', 'advice', 'equipment', 'software', 'news' sayılmır — heç vaxt -s almır.")],
 "q":[
 {"q":"'company' sözünün cəmi:","o":["companys","companies","companyes"],"a":1,"why":"Samit + y birləşməsində y düşür, -ies gəlir."},
 {"q":"Hansı SƏHVDİR?","o":["two children","three people","five informations"],"a":2,"why":"'information' sayılmayan isimdir, cəm forması yoxdur."},
 {"q":"'box' sözünün cəmi:","o":["boxs","boxes","boxies"],"a":1,"why":"-x ilə bitən sözlərə -es əlavə olunur."}]},

{"t":"Əvəzliklər — I / me / my","lv":"A1","s":[
 ("p","İngiliscədə əvəzlik cümlədəki roluna görə forma dəyişir. Azərbaycan dilində bunu hallar edir."),
 ("h","Üç sıra"),
 ("f","Mübtəda:  I · you · he · she · it · we · they"),
 ("f","Tamamlıq:  me · you · him · her · it · us · them"),
 ("f","Yiyəlik:  my · your · his · her · its · our · their"),
 ("e","I called him. ~ Mən ona zəng etdim."),
 ("e","He called me. ~ O mənə zəng etdi."),
 ("e","This is my laptop. ~ Bu mənim noutbukumdur."),
 ("h","Qayda"),
 ("p","Feldən ƏVVƏL — mübtəda forması. Feldən və ya sözönündən SONRA — tamamlıq forması. İsimdən əvvəl — yiyəlik forması."),
 ("x","Me and John went. ~ John and I went."),
 ("x","He gave the file to I. ~ He gave the file to me."),
 ("w","'its' (onun) və 'it's' (it is) tamam ayrı sözlərdir. Apostrof qısaltma deməkdir.")],
 "q":[
 {"q":"The manager called ___ yesterday.","o":["I","me","my"],"a":1,"why":"Feldən sonra tamamlıq forması gəlir."},
 {"q":"___ password is weak.","o":["You","Your","Yours"],"a":1,"why":"İsimdən əvvəl yiyəlik forması işlənir."},
 {"q":"Hansı düzdür?","o":["Its a good tool.","It's a good tool.","Its' a good tool."],"a":1,"why":"'It is' qısalanda 'it's' olur."}]},

{"t":"Present Simple — indiki qeyri-müəyyən","lv":"A1","s":[
 ("p","Adət, qayda, təkrarlanan hərəkət və dəyişməz həqiqətlər üçün işlənir. Ən çox işlənən zamandır."),
 ("f","I / you / we / they + fel      ·      he / she / it + fel + s"),
 ("e","I work at a bank. ~ Mən bankda işləyirəm."),
 ("e","She works at a bank. ~ O bankda işləyir."),
 ("e","Water boils at 100 degrees. ~ Su 100 dərəcədə qaynayır."),
 ("h","Üçüncü şəxs -s qaydası"),
 ("f","adi:  work → works   ·   -o, -sh, -ch, -x:  go → goes"),
 ("f","samit + y:  study → studies"),
 ("f","have → has"),
 ("h","İnkar və sual — do / does"),
 ("f","İnkar:  I do not (don't) work  ·  He does not (doesn't) work"),
 ("f","Sual:  Do you work?  ·  Does he work?"),
 ("w","Çox vacib: 'does' işlənəndə əsas fel -s İTİRİR."),
 ("x","Does he works here? ~ Does he work here?"),
 ("x","She work here. ~ She works here."),
 ("h","Tez-tez işlənən zaman sözləri"),
 ("f","always · usually · often · sometimes · never · every day")],
 "q":[
 {"q":"He ___ the logs every morning.","o":["check","checks","checking"],"a":1,"why":"He/she/it ilə felə -s əlavə olunur."},
 {"q":"Hansı düzdür?","o":["Does she works here?","Does she work here?","Do she work here?"],"a":1,"why":"'Does' varsa əsas fel sadə formada qalır."},
 {"q":"'Mən heç vaxt ehtiyat nüsxəni buraxmıram':","o":["I never skip backups.","I never skips backups.","I am never skip backups."],"a":0,"why":"'I' ilə fel dəyişmir və 'never' feldən əvvəl gəlir."}]},

{"t":"Sual qurmaq və söz sırası","lv":"A1","s":[
 ("p","Bu, Azərbaycan dilindən ən çox fərqlənən mövzudur. Bizdə söz sırası sərbəstdir, ingiliscədə isə sərt qaydadır."),
 ("f","Təsdiq:  MÜBTƏDA + FEL + TAMAMLIQ"),
 ("e","I sent the report. ~ Hesabatı göndərdim."),
 ("h","Sual sırası"),
 ("f","(Sual sözü) + KÖMƏKÇİ FEL + MÜBTƏDA + FEL"),
 ("e","Do you speak English? ~ İngiliscə danışırsınız?"),
 ("e","Where does he work? ~ O harada işləyir?"),
 ("e","When did you send it? ~ Nə vaxt göndərdiniz?"),
 ("h","Sual sözləri"),
 ("f","what nə · who kim · where harada · when nə vaxt"),
 ("f","why niyə · how necə · which hansı · whose kimin"),
 ("f","how much nə qədər · how many neçə · how long nə qədər müddət"),
 ("h","İki istisna"),
 ("p","'To be' və modal fellərlə (can, must, should) köməkçi fel lazım deyil — felin özü qabağa keçir."),
 ("e","Are you ready? ~ Hazırsınız?"),
 ("e","Can you help me? ~ Kömək edə bilərsiniz?"),
 ("x","Where you work? ~ Where do you work?"),
 ("x","You know what is the problem? ~ Do you know what the problem is?"),
 ("w","Cümlə içindəki sualda (dolayı sual) söz sırası NORMAL qalır: 'I know where he works', 'where does he work' yox.")],
 "q":[
 {"q":"Düzgün sual:","o":["Where he works?","Where does he work?","Where does he works?"],"a":1,"why":"Sual sözü + does + mübtəda + sadə fel."},
 {"q":"Dolayı sual üçün düzgün variant:","o":["Tell me where is the server.","Tell me where the server is.","Tell me where does the server."],"a":1,"why":"Cümlə içində söz sırası normal qalır."},
 {"q":"'Kömək edə bilərsiniz?'","o":["Do you can help me?","Can you help me?","Can do you help me?"],"a":1,"why":"Modal fellə köməkçi fel lazım deyil."}]},

{"t":"İnkar cümlələr","lv":"A1","s":[
 ("p","İngiliscədə inkar üçün 'not' işlənir, amma haraya qoyulacağı zamandan asılıdır."),
 ("f","to be:  am not · is not (isn't) · are not (aren't)"),
 ("f","Present Simple:  do not (don't) · does not (doesn't) + fel"),
 ("f","Past Simple:  did not (didn't) + fel"),
 ("f","Modal:  cannot (can't) · must not (mustn't) · should not (shouldn't)"),
 ("e","I do not have access. ~ Girişim yoxdur."),
 ("e","He didn't reply. ~ O cavab vermədi."),
 ("e","You mustn't share the password. ~ Şifrəni paylaşmaq olmaz."),
 ("h","İkiqat inkar OLMAZ"),
 ("p","Azərbaycan dilində 'heç nə bilmirəm' — iki inkar var. İngiliscədə yalnız bir inkar işlənir."),
 ("x","I don't know nothing. ~ I don't know anything."),
 ("x","He didn't saw it. ~ He didn't see it."),
 ("w","'did' və ya 'does' varsa əsas fel HƏMİŞƏ sadə formada qalır.")],
 "q":[
 {"q":"Hansı düzdür?","o":["He didn't sent it.","He didn't send it.","He not sent it."],"a":1,"why":"'didn't' varsa fel sadə formada qalır."},
 {"q":"'Heç nə görmədim':","o":["I didn't see nothing.","I didn't see anything.","I don't saw anything."],"a":1,"why":"İngiliscədə ikiqat inkar işlənmir."},
 {"q":"'Girişim yoxdur':","o":["I not have access.","I don't have access.","I doesn't have access."],"a":1,"why":"'I' ilə 'don't' işlənir."}]},

{"t":"There is / There are","lv":"A1","s":[
 ("p","Nəyinsə mövcud olduğunu bildirmək üçün. Azərbaycan dilindəki 'var' sözünün qarşılığıdır."),
 ("f","There is + tək isim      ·      There are + cəm isim"),
 ("e","There is a problem with the server. ~ Serverdə problem var."),
 ("e","There are three users online. ~ Üç istifadəçi onlayndır."),
 ("h","İnkar və sual"),
 ("f","There isn't any... · There aren't any..."),
 ("f","Is there...? · Are there...?"),
 ("e","Is there a backup? ~ Ehtiyat nüsxə var?"),
 ("e","There isn't enough space. ~ Kifayət qədər yer yoxdur."),
 ("h","Keçmiş zaman"),
 ("f","There was (tək)  ·  There were (cəm)"),
 ("e","There was an outage last night. ~ Dünən gecə kəsinti oldu."),
 ("x","Have a problem in the server. ~ There is a problem with the server."),
 ("w","'It is' ilə qarışdırma. 'There is' = var. 'It is' = odur.")],
 "q":[
 {"q":"___ two errors in the log.","o":["There is","There are","It is"],"a":1,"why":"'errors' cəmdir, 'there are' işlənir."},
 {"q":"'Ehtiyat nüsxə var?'","o":["Is there a backup?","Is it a backup?","Have a backup?"],"a":0,"why":"Mövcudluq sualı 'Is there...?' ilə qurulur."},
 {"q":"'Dünən kəsinti oldu':","o":["There is an outage yesterday.","There was an outage yesterday.","There were an outage yesterday."],"a":1,"why":"Keçmiş + tək isim = 'There was'."}]},

{"t":"Can / Could — bacarıq və icazə","lv":"A1","s":[
 ("p","'Can' modal feldir. Modal fellərdən sonra fel HƏMİŞƏ sadə formada gəlir — nə -s, nə -ed, nə 'to'."),
 ("f","can + fel (sadə forma)"),
 ("e","I can read technical documents. ~ Texniki sənədləri oxuya bilirəm."),
 ("e","She can speak three languages. ~ O üç dildə danışa bilir."),
 ("h","İnkar və sual"),
 ("f","cannot = can't      ·      Can you...?"),
 ("e","I can't open the file. ~ Faylı aça bilmirəm."),
 ("h","Could — daha nəzakətli və keçmiş"),
 ("e","Could you send me the report? ~ Hesabatı göndərə bilərsinizmi?"),
 ("e","I could not connect yesterday. ~ Dünən qoşula bilmədim."),
 ("x","I can to help you. ~ I can help you."),
 ("x","He cans speak English. ~ He can speak English."),
 ("w","Modal fel heç vaxt -s almır və ondan sonra 'to' gəlmir.")],
 "q":[
 {"q":"Hansı düzdür?","o":["She can helps you.","She can help you.","She can to help you."],"a":1,"why":"Modaldan sonra fel sadə formada gəlir."},
 {"q":"Nəzakətli xahiş:","o":["Can you send it?","Could you send it?","You send it?"],"a":1,"why":"'Could' daha nəzakətlidir, rəsmi yazışmada istifadə olunur."},
 {"q":"'Qoşula bilmirəm':","o":["I can't connect.","I don't can connect.","I am not can connect."],"a":0,"why":"Modalın öz inkarı var: cannot / can't."}]},

{"t":"Sözönləri — in / on / at","lv":"A1","s":[
 ("p","Sözönləri əzbərlənir, məntiqlə tapılmır. Ən çox işlənən üçünü mütləq mənimsə."),
 ("h","ZAMAN"),
 ("f","at + dəqiq saat:  at 9 o'clock, at noon, at night"),
 ("f","on + gün və tarix:  on Monday, on 5 May"),
 ("f","in + ay, il, fəsil, hissə:  in May, in 2026, in the morning"),
 ("e","The meeting is at 10 on Monday. ~ İclas bazar ertəsi saat 10-dadır."),
 ("h","YER"),
 ("f","at + nöqtə:  at the office, at home, at the door"),
 ("f","on + səth:  on the table, on the wall, on page 5"),
 ("f","in + içəri:  in the room, in Baku, in the file"),
 ("e","The file is on the desktop, in the reports folder. ~ Fayl masaüstündə, hesabatlar qovluğundadır."),
 ("h","Əzbərlənəsi ifadələr"),
 ("f","at work · at school · at home · in time · on time"),
 ("f","in the morning AMMA on Monday morning"),
 ("x","I am in work. ~ I am at work."),
 ("x","See you in Monday. ~ See you on Monday."),
 ("w","'on time' = vaxtında. 'in time' = vaxt çatmamış. Fərqlidirlər.")],
 "q":[
 {"q":"The audit is ___ September.","o":["at","on","in"],"a":2,"why":"Ay adları ilə 'in' işlənir."},
 {"q":"I start work ___ 9 o'clock.","o":["at","on","in"],"a":0,"why":"Dəqiq saatla 'at' işlənir."},
 {"q":"Hansı düzdür?","o":["I am in work now.","I am at work now.","I am on work now."],"a":1,"why":"'at work' sabit ifadədir."}]},
]
