# -*- coding: utf-8 -*-
"""Kolge texnikasi ucun uzun, tebii nitq parcalari.
Her sətir 15-30 soz - baglı nitq (connected speech) mesqi ucun.
"""

SHADOW = [
{"t":"Səsli mesaj qoymaq","lv":"A2","d":"Telefon açılmayanda mesaj buraxmaq","l":[
 ("Hi, this is Samir calling from Bank Melli. I am trying to reach Ilyas about the API integration.",
  "Salam, Bank Melli-dən Samir zəng edir. İlyası API inteqrasiyası barədə axtarıram."),
 ("I sent you an email on Monday, but I have not heard back, so I thought I would give you a call.",
  "Bazar ertəsi e-poçt göndərdim, amma cavab almadım, ona görə zəng etmək istədim."),
 ("The short version is that we are still getting an authentication error on the test gateway.",
  "Qısası, test şlüzündə hələ də autentifikasiya xətası alırıq."),
 ("If you could send over the correct header name, I think we could close this off in about ten minutes.",
  "Düzgün başlıq adını göndərsəniz, məncə bunu on dəqiqəyə bağlaya bilərik."),
 ("You can reach me on this number any time before six, or just reply to my email if that is easier.",
  "Altıya qədər bu nömrədən mənə çata bilərsiniz, ya da asandırsa e-poçtuma cavab yazın."),
 ("Thanks a lot, and I look forward to hearing from you. Bye for now.",
  "Çox sağ olun, cavabınızı gözləyirəm. Hələlik.")]},

{"t":"İclasda status hesabatı","lv":"B1","d":"Həftəlik görüşdə vəziyyəti danışmaq","l":[
 ("Right, let me give you a quick update on where we are with the migration project.",
  "Yaxşı, miqrasiya layihəsində harada olduğumuz barədə qısa məlumat verim."),
 ("We finished the first two modules last week, and both of them passed testing without any major issues.",
  "Keçən həftə ilk iki modulu bitirdik və hər ikisi ciddi problem olmadan testdən keçdi."),
 ("The third module is about eighty percent complete, but we have run into a small problem with the reporting layer.",
  "Üçüncü modul təxminən səksən faiz hazırdır, amma hesabat qatında kiçik problemlə üzləşdik."),
 ("Nothing serious, it just means we are running roughly two days behind the original schedule.",
  "Ciddi bir şey deyil, sadəcə ilkin cədvəldən təxminən iki gün geridəyik."),
 ("If nothing else comes up, I am confident we can make that time back before the end of the month.",
  "Başqa problem çıxmasa, ayın sonuna qədər bu vaxtı bərpa edə biləcəyimizə əminəm."),
 ("The only thing I need from you is sign-off on the extra test environment, ideally by Wednesday.",
  "Sizdən yalnız əlavə test mühiti üçün təsdiq lazımdır, ideal halda çərşənbəyə qədər."),
 ("Other than that, everything is on track. Happy to take any questions.",
  "Bundan başqa hər şey qaydasındadır. Suallarınıza cavab verməyə hazıram.")]},

{"t":"İnsident brifinqi","lv":"B2","d":"Kəsintidən sonra rəhbərliyə hesabat","l":[
 ("I want to walk you through what happened yesterday evening and what we have done since then.",
  "Dünən axşam nə baş verdiyini və o vaxtdan bəri nə etdiyimizi izah etmək istəyirəm."),
 ("At around seven o'clock, users started reporting that they could not log into internet banking.",
  "Saat yeddi radələrində istifadəçilər internet bankçılığa girə bilmədiklərini bildirməyə başladılar."),
 ("Our first assumption was a database problem, but the database was responding perfectly normally.",
  "İlk fərziyyəmiz verilənlər bazası problemi idi, amma baza tamamilə normal cavab verirdi."),
 ("It turned out that the certificate on the load balancer had expired, and the renewal had only been applied to one of the two nodes.",
  "Məlum oldu ki, yük balanslaşdırıcıdakı sertifikatın müddəti bitib və yeniləmə iki qovşaqdan yalnız birinə tətbiq olunub."),
 ("We replaced it and restarted the service, and everything came back up within about forty minutes.",
  "Onu dəyişdik və xidməti yenidən başlatdıq, hər şey təxminən qırx dəqiqəyə bərpa oldu."),
 ("The total impact was around ninety minutes of degraded service for roughly two thousand customers.",
  "Ümumi təsir təxminən iki min müştəri üçün doxsan dəqiqəlik pozulmuş xidmət oldu."),
 ("To stop this happening again, we have set up automated monitoring on every certificate we own.",
  "Bunun təkrarlanmaması üçün sahib olduğumuz hər sertifikata avtomatik monitorinq qurmuşuq."),
 ("It now alerts us thirty days before expiry, and it checks both nodes rather than just the primary one.",
  "İndi bitməsinə otuz gün qalmış xəbərdarlıq edir və yalnız əsas deyil, hər iki qovşağı yoxlayır.")]},

{"t":"Müştəriyə problemi izah etmək","lv":"B1","d":"Texniki məsələni sadə dillə çatdırmaq","l":[
 ("Thank you for holding, and I am sorry about the wait. Let me explain what is going on.",
  "Gözlədiyiniz üçün təşəkkür və gecikməyə görə üzr istəyirəm. İcazə verin nə baş verdiyini izah edim."),
 ("The problem you are seeing is not with your account, so there is nothing wrong on your side at all.",
  "Gördüyünüz problem hesabınızla bağlı deyil, sizin tərəfinizdə heç bir nasazlıq yoxdur."),
 ("What has happened is that one of our servers is running slowly, and that is delaying some transactions.",
  "Baş verən odur ki, serverlərimizdən biri yavaş işləyir və bu, bəzi əməliyyatları gecikdirir."),
 ("Your money is completely safe, and every transaction you made today has been recorded correctly.",
  "Pulunuz tamamilə təhlükəsizdir və bu gün etdiyiniz hər əməliyyat düzgün qeydə alınıb."),
 ("Our engineers are working on it right now, and we expect everything to be back to normal within the hour.",
  "Mühəndislərimiz elə indi bunun üzərində işləyir, bir saat ərzində hər şeyin normala qayıtmasını gözləyirik."),
 ("If you would like, I can take your number and call you personally as soon as it is resolved.",
  "İstəsəniz, nömrənizi götürüb həll olunan kimi şəxsən sizə zəng edə bilərəm."),
 ("Again, I really do apologise for the inconvenience, and thank you for being so patient with us.",
  "Bir daha narahatlığa görə səmimi üzr istəyirəm və səbrinizə görə təşəkkür edirəm.")]},

{"t":"Müsahibə: özünüz haqqında","lv":"B2","d":"Ən çox verilən suala hazır cavab","l":[
 ("Of course. I have been working in banking technology for just over ten years now.",
  "Əlbəttə. On ildən çoxdur ki, bank texnologiyaları sahəsində işləyirəm."),
 ("I started out in support, moved into networking after a couple of years, and now I run the whole IT function.",
  "Dəstək xidmətindən başladım, bir neçə ildən sonra şəbəkəyə keçdim, indi isə bütün İT funksiyasına rəhbərlik edirəm."),
 ("In my current role I am responsible for infrastructure, information security, and regulatory reporting.",
  "Hazırkı vəzifəmdə infrastruktur, informasiya təhlükəsizliyi və tənzimləyici hesabatlara görə məsulam."),
 ("It is quite a broad role, mainly because we are a small branch, so I tend to do a bit of everything.",
  "Kifayət qədər geniş vəzifədir, əsasən ona görə ki, kiçik filialıq, ona görə hər işdən bir az görürəm."),
 ("The part I enjoy most is building things, and the platform we use internally is something I designed from scratch.",
  "Ən çox zövq aldığım hissə bir şey qurmaqdır, daxildə istifadə etdiyimiz platformanı sıfırdan özüm dizayn etmişəm."),
 ("What I am looking for now is a role where I can go deeper on the infrastructure side and work with a larger team.",
  "İndi axtardığım infrastruktur tərəfində daha dərinə getmək və daha böyük komanda ilə işləmək imkanıdır."),
 ("That is really why this position caught my eye, and I would be glad to go into any part of it in more detail.",
  "Bu vəzifənin diqqətimi çəkməsinin əsl səbəbi budur, istənilən hissəsini daha ətraflı danışmağa şadam.")]},

{"t":"Təqdimatın açılışı","lv":"B2","d":"Auditoriya qarşısında başlamaq","l":[
 ("Good morning, everyone, and thank you all for making the time to be here today.",
  "Sabahınız xeyir hamıya, bu gün burada olmaq üçün vaxt ayırdığınıza görə təşəkkür."),
 ("For those who do not know me, my name is Samir and I head up the IT department at the Baku branch.",
  "Məni tanımayanlar üçün deyim, adım Samirdir və Bakı filialında İT şöbəsinə rəhbərlik edirəm."),
 ("Over the next twenty minutes I want to cover three things, and then leave plenty of room for questions.",
  "Növbəti iyirmi dəqiqədə üç məsələni əhatə etmək və sonra suallar üçün kifayət qədər vaxt saxlamaq istəyirəm."),
 ("First, where we are today. Second, the main risks I think we are carrying. And third, what I would suggest we do about them.",
  "Birincisi, bu gün harada olduğumuz. İkincisi, daşıdığımızı düşündüyüm əsas risklər. Üçüncüsü isə bu barədə nə etməyi təklif etdiyim."),
 ("I will try to keep the technical detail to a minimum, but do stop me at any point if something is not clear.",
  "Texniki detalları minimumda saxlamağa çalışacağam, amma nəsə aydın olmasa istənilən anda məni saxlayın."),
 ("So, let us start with a quick look at where things stand right now.",
  "Beləliklə, hazırkı vəziyyətə qısa nəzər salmaqla başlayaq.")]},

{"t":"Yeni işçiyə sistemi izah etmək","lv":"B1","d":"Addım-addım prosesi çatdırmaq","l":[
 ("Right, let me show you how the system works, and then you can have a go yourself.",
  "Yaxşı, sistemin necə işlədiyini göstərim, sonra özünüz sınayarsınız."),
 ("The first thing you need to do every morning is log in and check whether the overnight jobs completed.",
  "Hər səhər ilk etməli olduğunuz şey giriş etmək və gecə işlərinin tamamlandığını yoxlamaqdır."),
 ("If any of them failed, you will see a red flag next to the job name, and the details are in the log below.",
  "Onlardan biri uğursuz olsa, iş adının yanında qırmızı bayraq görəcəksiniz, təfərrüatlar isə aşağıdakı jurnaldadır."),
 ("Nine times out of ten it is just a network timeout, so you can simply run it again and it will go through.",
  "On haldan doqquzunda bu sadəcə şəbəkə vaxt aşımıdır, yenidən işə salsanız keçəcək."),
 ("If it fails a second time, do not keep retrying. Take a screenshot and send it to me straight away.",
  "İkinci dəfə də uğursuz olsa, təkrar cəhd etməyin. Ekran şəkli çəkin və dərhal mənə göndərin."),
 ("The most important rule is that you never change anything in production without telling someone first.",
  "Ən vacib qayda budur ki, kiməsə demədən istehsalat mühitində heç nəyi dəyişməyin."),
 ("Other than that, feel free to click around and explore. You cannot break anything from this screen.",
  "Bundan başqa, rahat kliklə və araşdır. Bu ekrandan heç nəyi sındıra bilməzsən.")]},

{"t":"Vendorla telefon danışığı","lv":"B2","d":"Şərtləri müzakirə etmək","l":[
 ("Hi Michael, thanks for taking the call. I have had a chance to look through the proposal you sent.",
  "Salam Michael, zəngi qəbul etdiyiniz üçün təşəkkür. Göndərdiyiniz təklifə baxmaq imkanım oldu."),
 ("Overall it looks solid, and the technical side is more or less exactly what we were hoping for.",
  "Ümumilikdə möhkəm görünür, texniki tərəf az-çox tam gözlədiyimiz kimidir."),
 ("Where I am struggling a little is the pricing, particularly the licence cost for the first year.",
  "Bir az çətinlik çəkdiyim yer qiymətdir, xüsusən də ilk il üçün lisenziya xərci."),
 ("The figure you quoted is roughly thirty percent above what we have set aside in this year's budget.",
  "Göstərdiyiniz rəqəm bu ilki büdcəmizdə ayırdığımızdan təxminən otuz faiz yuxarıdır."),
 ("I am not asking you to cut your margin. I am wondering whether we could start with fewer user seats.",
  "Sizdən marjanızı azaltmağı xahiş etmirəm. Daha az istifadəçi yeri ilə başlaya bilərikmi deyə düşünürəm."),
 ("If we began with sixty and added more as we roll out, would that work from your side?",
  "Altmışla başlayıb tətbiq etdikcə artırsaq, sizin tərəfdən bu uyğun olar?"),
 ("If you could put a revised version together by Friday, I can take it to the board next week.",
  "Cüməyə qədər yenilənmiş variant hazırlaya bilsəniz, gələn həftə idarə heyətinə təqdim edərəm.")]},

{"t":"Həftəsonundan danışmaq","lv":"A2","d":"Gündəlik söhbət — ən çox lazım olan","l":[
 ("It was pretty quiet, actually. I did not have any big plans, which was honestly a relief.",
  "Əslində olduqca sakit keçdi. Böyük planım yox idi, düzü bu rahatlıq idi."),
 ("On Saturday morning I slept in for once, and then I spent a couple of hours working on the flat.",
  "Şənbə səhəri bir dəfəlik gec yatdım, sonra bir neçə saat mənzillə məşğul oldum."),
 ("I have been meaning to finish painting the kitchen for about three months, so I finally made a start.",
  "Təxminən üç aydır mətbəxi rəngləməyi bitirmək istəyirdim, nəhayət başladım."),
 ("In the afternoon we drove out of the city and had lunch at a place near the coast.",
  "Günortadan sonra şəhərdən çıxdıq və sahilə yaxın bir yerdə nahar etdik."),
 ("Sunday was mostly family. My parents came over, we had a long lunch, and I did not touch the laptop once.",
  "Bazar günü əsasən ailə ilə keçdi. Valideynlərim gəldi, uzun nahar etdik və noutbuka bir dəfə də toxunmadım."),
 ("So nothing exciting, but that is exactly what I needed. How about you, did you get up to much?",
  "Yəni maraqlı bir şey yox, amma mənə elə bu lazım idi. Bəs sən, nəsə etdin?")]},

{"t":"Səyahət təcrübəsi","lv":"B1","d":"Hekayə danışmaq — keçmiş zaman məşqi","l":[
 ("The trip I always end up talking about is the one I took to Istanbul a few years ago.",
  "Həmişə danışdığım səfər bir neçə il əvvəl İstanbula etdiyim səfərdir."),
 ("I only went for four days, mainly for a conference, but I managed to see quite a lot in that time.",
  "Cəmi dörd gün getmişdim, əsasən konfrans üçün, amma o müddətdə xeyli şey görməyi bacardım."),
 ("What surprised me most was how walkable the old part of the city is once you get away from the main roads.",
  "Məni ən çox təəccübləndirən əsas yollardan uzaqlaşanda şəhərin köhnə hissəsinin nə qədər piyada gəzilə bilən olması idi."),
 ("On the second evening I got completely lost, and I ended up in a small street full of tiny restaurants.",
  "İkinci axşam tamam yolumu itirdim və kiçik restoranlarla dolu balaca bir küçəyə düşdüm."),
 ("I had the best meal of the whole trip there, and I still could not tell you the name of the place.",
  "Bütün səfərin ən yaxşı yeməyini orada yedim və hələ də o yerin adını deyə bilmərəm."),
 ("If I went back tomorrow, I would stay longer and spend far less time in conference rooms.",
  "Sabah qayıtsaydım, daha uzun qalar və konfrans zallarında xeyli az vaxt keçirərdim.")]},

{"t":"Fikri müdafiə etmək","lv":"B2","d":"Arqument qurmaq və mövqe tutmaq","l":[
 ("I know this is not a popular view in the room, but I think we are approaching the problem from the wrong end.",
  "Bilirəm ki, bu, otaqda populyar fikir deyil, amma məncə problemə səhv tərəfdən yanaşırıq."),
 ("Everyone is focused on buying a new tool, when the real issue is that nobody owns the process.",
  "Hamı yeni alət almağa fokuslanıb, halbuki əsl problem odur ki, prosesin sahibi yoxdur."),
 ("We could spend a hundred thousand manats tomorrow and still be having this same conversation next year.",
  "Sabah yüz min manat xərcləyə bilərik və gələn il yenə eyni söhbəti edərik."),
 ("What I would suggest instead is that we start small, fix the process, and only then look at tooling.",
  "Əvəzində təklifim budur ki, kiçikdən başlayaq, prosesi düzəldək və yalnız ondan sonra alətlərə baxaq."),
 ("That gives us something working within a month rather than a project that drags on for a year.",
  "Bu, bir il uzanan layihə əvəzinə bir ay ərzində işləyən bir şey verir."),
 ("I am obviously happy to be persuaded otherwise, but I would want to see the numbers first.",
  "Əlbəttə, əksinə inandırılmağa açığam, amma əvvəlcə rəqəmləri görmək istərdim.")]},

{"t":"Xəbəri şərh etmək","lv":"B1","d":"Oxuduğunu təkrar danışmaq","l":[
 ("I read something interesting this morning about how banks are starting to use artificial intelligence.",
  "Bu səhər bankların süni intellektdən istifadəyə necə başladığı barədə maraqlı bir şey oxudum."),
 ("Apparently most of them are not using it for anything customer facing yet, which surprised me a bit.",
  "Görünür, onların əksəriyyəti hələ müştəriyə yönəlik heç nədə istifadə etmir, bu məni bir az təəccübləndirdi."),
 ("The main use so far seems to be internal, things like detecting fraud and speeding up reporting.",
  "İndiyə qədər əsas istifadə daxili görünür — fırıldaqçılığın aşkarlanması və hesabatın sürətləndirilməsi kimi."),
 ("What struck me was the point about small banks, because they simply do not have the data volume.",
  "Məni vuran kiçik banklar barədə fikir oldu, çünki onlarda sadəcə kifayət qədər məlumat həcmi yoxdur."),
 ("So the gap between the large players and everyone else could actually get wider, not narrower.",
  "Yəni böyük oyunçularla qalanlar arasındakı fərq daralmaq əvəzinə genişlənə bilər."),
 ("I am not sure I agree with all of it, but it is definitely worth a read if you get five minutes.",
  "Hər şeyi ilə razı olduğuma əmin deyiləm, amma beş dəqiqəniz olsa oxumağa dəyər.")]},

{"t":"Şikayətə cavab vermək","lv":"B2","d":"Gərgin vəziyyəti sakitləşdirmək","l":[
 ("First of all, I want to say that you are completely right to be frustrated, and I am not going to argue with that.",
  "İlk növbədə demək istəyirəm ki, narazı olmaqda tamamilə haqlısınız və mən bununla mübahisə etməyəcəyəm."),
 ("Waiting three days for a reply is not the standard we set for ourselves, and it should not have happened.",
  "Cavab üçün üç gün gözləmək özümüzə qoyduğumuz standart deyil və bu baş verməməli idi."),
 ("I have looked at your ticket, and I can see exactly where it went wrong. It was never escalated.",
  "Müraciətinizə baxdım və harada səhv getdiyini dəqiq görürəm. O, heç vaxt yuxarı qaldırılmayıb."),
 ("That is on us, not on you, and I am not going to try to explain it away as a system problem.",
  "Bu bizim təqsirimizdir, sizin yox və mən bunu sistem problemi kimi izah etməyə çalışmayacağam."),
 ("What I am going to do is take ownership of this personally and stay on it until it is closed.",
  "Edəcəyim şey budur ki, bunu şəxsən öz üzərimə götürəcəyəm və bağlanana qədər izləyəcəyəm."),
 ("You will hear from me before five o'clock today, whether I have a full answer or not.",
  "Tam cavabım olsun ya olmasın, bu gün saat beşə qədər məndən xəbər alacaqsınız."),
 ("And if you are still not happy after that, my direct number is on the email I am about to send you.",
  "Ondan sonra da razı qalmasanız, birbaşa nömrəm indi göndərəcəyim e-poçtdadır.")]},

{"t":"Prosesi izah etmək","lv":"B1","d":"Ardıcıllıq bildirən bağlayıcılar","l":[
 ("The process itself is fairly simple once you have done it a couple of times, so do not worry about it.",
  "Bir neçə dəfə etdikdən sonra prosesin özü kifayət qədər sadədir, ona görə narahat olmayın."),
 ("To begin with, you export the raw data from the core system, and you save it as a CSV file.",
  "Əvvəlcə əsas sistemdən xam məlumatı ixrac edirsiniz və CSV faylı kimi saxlayırsınız."),
 ("Once you have done that, you open the reporting template and you run the macro from the ribbon.",
  "Bunu etdikdən sonra hesabat şablonunu açıb lentdən makronu işə salırsınız."),
 ("The macro will ask you to select the file, and after that it does everything else automatically.",
  "Makro sizdən faylı seçməyi xahiş edəcək, ondan sonra qalan hər şeyi avtomatik edir."),
 ("While it is running, do not touch the keyboard, because it will pick up whatever cell you land on.",
  "İşləyərkən klaviaturaya toxunmayın, çünki hansı xanaya düşsəniz onu götürəcək."),
 ("Finally, you check that the totals at the bottom match the control figure, and then you submit it.",
  "Nəhayət, aşağıdakı cəmlərin nəzarət rəqəminə uyğun gəldiyini yoxlayır və təqdim edirsiniz."),
 ("The whole thing takes about ten minutes, and most of that is just waiting for the export to finish.",
  "Bütün bu iş təxminən on dəqiqə çəkir və onun çoxu sadəcə ixracın bitməsini gözləməkdir.")]},
]
